version : "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "qwerty"

  mongo-express:
    image : mongo-express
    container_name: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "qwerty"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:qwerty@mongo:27017"
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    depends_on:
      - mongo
  docker-testapp:
    image: ujjwal82nl/testapp
    container_name: test-app
    ports:
    - 5050:5050
    environment:
      MONGO_URL: "mongodb://admin:qwerty@mongo:27017"
    depends_on:
    - mongo

volumes:
  mongo-data:
